name: Python Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.arch == 'arm64' && format('{0}-{1}', matrix.os, matrix.arch) || matrix.os }}
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: windows
            arch: amd64
          - os: windows
            arch: arm64
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          cache: 'pip'


      - name: Upgrade setuptools, wheel, and install requirements
        run: |
          pip install --upgrade setuptools wheel pyinstaller~=5.13.2 && pip install -r requirements.txt


      - name: Build Pyinstaller
        shell: bash
        run: |
          PLAYWRIGHT_BROWSERS_PATH=0 playwright install chromium
          pyinstaller main.spec
      - name: Zip the Build-windows
        if: matrix.os == 'windows'
        run: Compress-Archive -Path ./dist/biliTicKerBuy.exe -DestinationPath tmp.zip

      - name: Zip the Build-linux
        if: matrix.os == 'linux'
        run: |
          cd ./dist
          zip -r  ../tmp.zip biliTickerBuy

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: tmp.zip
          asset_name: ${{ secrets.ReleaseZipName }}_${{ matrix.os }}_${{ matrix.arch }}_${{ github.ref_name }}.zip
          tag: ${{ github.ref }}
          overwrite: true
